### ISSUE TITLE
Boot Loop after 1st Installer Reboot

### ISSUE THREAD

**Issue by AwlsomeAlex** [valnoxy/t440p-oc#10]
Hello,
I tried using the latest release (v1.4.0) with macOS 11.2.3 and 11.4.
I am able to boot into the macOS Installer and initialize the install, but after the first reboot my laptop goes into a boot loop.
The boot menu will appear once and I'll select "macOS Installer", but after that it panics and goes into a boot loop, where the OC menu won't even appear.
I also had some issues in 11.4 where it would mess with my EFI bootloader, with the BIOS having to recover some EFI variables.
I can supply more information as requested. Thanks!
The only thing non-baseline about my T440p is that it has an FHD IPS screen mod.

**Comment by turbo-cafe** [comment]
@AwlsomeAlex did you figure out the reason for boot loop? I've got same thing going on.
