### ISSUE TITLE
iPhone USB triggers nonstop "Trust this device" message loop

### ISSUE THREAD

**Issue by nubilate** [valnoxy/t440p-oc#11]
- macOS 11.4 under EFI - Big Sur 

When I plug my iPhone into my hackintoshed T440p into almost every port, I get a looped "Trust this device" message popup. I say almost because one of the USB ports only provide power (the one with usb and a label for a battery on the right side). I swapped cables and ports, and I still get the same result. Any suggestions? Let me know if you need any further documentation.

**Comment by valnoxy** [comment]
I released Version 1.5.0. Does this issue still exist in this version?

**Comment by nubilate** [comment]
The update fixed it, thank you!
