### ISSUE TITLE
Docking Station Compatibility

### ISSUE THREAD

**Issue by retracee** [valnoxy/t440p-oc#12]
This isn't an issue, but I want to report that the docking station's USB ports, displayport, and VGA ports all work. Thank you for the great hackintosh guide

**Comment by valnoxy** [comment]
Thanks! I will update the readme. 👍

**Comment by Xeceryn** [comment]
Hello @valnoxy , I have problem with Docking Station when i reboot or shutdown my device, its not shutdown properly

**Comment by Xeceryn** [comment]
> This isn't an issue, but I want to report that the docking station's USB ports, displayport, and VGA ports all work. Thank you for the great hackintosh g

> This isn't an issue, but I want to report that the docking station's USB ports, displayport, and VGA ports all work. Thank you for the great hackintosh guide

Have you tried to reboot, sleep, or turn off the laptop when plugged in the docking station
