### ISSUE TITLE
Upgrade to Big Sur from Catalina

### ISSUE THREAD

**Issue by melihcoban** [valnoxy/t440p-oc#13]
Hi! Thanks for the such a detailed guide, I installed Catalina without any issues. I was wondering if I can update to Big Sur inside macOS now or do I need to follow the same steps again and install it by downloading Big Sur? Are there any specifics precautions I need to take? Sorry I'm new at Hackintosh and I don't want to broke something while updating :D It would be great if you write a process about updating as well.

**Comment by valnoxy** [comment]
Hey! I updated the readme with a guide how to upgrade to a newer release of macOS. 
[Upgrade macOS / Switch or update EFI »](https://github.com/valnoxy/t440p-oc#%EF%B8%8F-upgrade-macos--switch-efi)
