### ISSUE TITLE
EFI Name

### ISSUE THREAD

**Issue by tomassasovsky** [valnoxy/t440p-oc#15]
I have macOS, Arch Linux and Windows 11 installed on my T440P.
When I boot up, macOS gives me multiple options: Windows, Macintosh, and NO-NAME (this one being Arch).
Is there any way to change the order and names on this screen?

**Comment by valnoxy** [comment]
Hey! To fix the issue with "NO-NAME", try to rename the Arch partition label. You could do it via the command line or via a GUI app like Gparted. The boot order cannot be reordered as I know, but you can change the default boot volume by going in macOS to Settings -> Startup disk.
