### ISSUE TITLE
Sidecar not working

### ISSUE THREAD

**Issue by SolomonPeggs** [valnoxy/t440p-oc#17]
Sidecar isn't supported. Any plans on enabling this feature?

**Comment by valnoxy** [comment]
Hey, thanks for your feedback!
I include Sidecar support with Version 1.5.1.

**Comment by SolomonPeggs** [comment]
Hey, I tried to update my EFI. and now I cant boot into open core. Any help?

**Comment by valnoxy** [comment]
I re-upload the version with a bugfix.
