### ISSUE TITLE
Can't Wake Up From Sleep.

### ISSUE THREAD

**Issue by tomassasovsky** [valnoxy/t440p-oc#19]
Can't wake up from sleep.

 - macOS Version: Big Sur 11.3.1
 - EFI Version: 1.5.0
 - EFI type (regular or HeliPort): Regular

When the laptop goes into sleep, I press the power key to wake it up, but this doesn't work.
I have to shut it down and power it up again.

**Comment by valnoxy** [comment]
Is the security chip enabled? If yes, try to disable it. Apparently it looks like the TPM module is interfering with macOS when it wakes up. I will try to find a alternative way but in the meantime, I recommend disabling TPM if it is enabled.

**Comment by narvikd** [comment]
Any news on this? Is sleeping working for others?

**Comment by melihcoban** [comment]
> Any news on this? Is sleeping working for others?

It is working fine for me. It goes to sleep when I close the lid or after 30 minutes for energy saving, and wakes up without a problem.

**Comment by narvikd** [comment]
> It is working fine for me. It goes to sleep when I close the lid or after 30 minutes for energy saving, and wakes up without a problem.

Have you done anything different from what it says in the tutorial? Thanks!

**Comment by melihcoban** [comment]
> > It is working fine for me. It goes to sleep when I close the lid or after 30 minutes for energy saving, and wakes up without a problem.
> 
> Have you done anything different from what it says in the tutorial? Thanks!

No, not at all. Like valnoxy said I believe it might have to do something with the BIOS settings. It is fine in both Catalina and Big Sur.
