### ISSUE TITLE
Monterey update does not work.

### ISSUE THREAD

**Issue by Jcdowen** [valnoxy/t440p-oc#21]
See photo attached
![IMG_20210802_032205_edit_22751816852777](https://user-images.githubusercontent.com/26368378/127806408-bfbb2974-8f34-4252-9e6c-2ca9742675a9.jpg)

**Comment by Jcdowen** [comment]
I should also point out the exact same config boots into Big Sur and has absolutely no issues.

**Comment by Jcdowen** [comment]
I managed to fix this, the fix is as follows.

1. Double check your bios is set correctly according to the guide, even the seemingly mundane settings are very important.

2. Swap the ITLWM .kext with the newest DEBUG version (v2.0.0-alpha at the time of writing).
https://github.com/OpenIntelWireless/itlwm/releases

3. Swap the bluetooth .kext with the newest DEBUG version (V2.0.0 RC2 at the time of writing).
https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases

4. follow this guide to get the correct bluetooth .kext configuration, if you don't Bluetooth and Ultrabay HDD's will not work, and you will have a very long boot time with lots of errors.
https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/295#issuecomment-861075343

5. use ProperTree (or your plist editor of choice) and  take a clean snapshot of your EFI.

6. Create a USB installer of Monterey and boot from it with your new EFI.

Job Done :)

**Comment by FxPixels** [comment]
the same problom, @Jcdowen could you please share you EFI ? thanks.

**Comment by Jcdowen** [comment]
[EFI - Monterey.zip](https://github.com/valnoxy/t440p-oc/files/6988569/EFI.-.Monterey.zip)

Here you go @FxPixels :).

(Generate your own SMBIOS info with:
https://github.com/corpnewt/GenSMBIOS
