### ISSUE TITLE
Netflix does not work on Safari

### ISSUE THREAD

**Issue by melihcoban** [valnoxy/t440p-oc#24]
**Describe the bug**
Playing something on Netflix in Safari gives me an error code of "S7706" and playback does not work. I do not have the same problem in Firefox. 

**Screenshots**
[Screenshot of the issue](https://imgur.com/a/pn3h4RR)

**Device (please complete the following information):**
 - macOS Version: Big Sur 11.4 
 - EFI Version: Latest version
 - EFI type (regular or HeliPort): Regular

**Comment by Gopherslol** [comment]
My understanding is that this is a DRM issue which applies to all hackintoshes running newish releases. Only workaround is to use a different browser

**Comment by valnoxy** [comment]
You're right, DRM is broken. This is due to the issue that the iGPU don't support Apple's firmware. The DRM patches by WhateverGreen are also not working since Safari 14 and macOS Big Sur. You can find more about DRM here: https://dortania.github.io/OpenCore-Post-Install/universal/drm.html
