### ISSUE TITLE
Boot Camp Assistant (Windows)

### ISSUE THREAD

**Issue by tomassasovsky** [valnoxy/t440p-oc#25]
I've been trying to create a Windows 10 partition using Boot Camp Assistant, but always get an error that says "Your disk couldn't be partitioned"

I've tried every possible solution on the mac's support pages, but still no luck. That's why I was thinking that it may be related to the t440p.

Do you know any way to do this properly?
Thanks.

**Comment by valnoxy** [comment]
Hey👋, I have added the missing drivers to this repo.
