### ISSUE TITLE
Cannot get any WiFi signal, no bluetooth

### ISSUE THREAD

**Issue by Hunterttt** [valnoxy/t440p-oc#26]
**Describe the bug**
Hi, I installed Big Sur, there are 2 bugs on my T440p
1, Cannot get any WiFi signal.
2, No bluetooth, bluetooth can work well in Win10.

**Screenshots**
![1 (3)](https://user-images.githubusercontent.com/58203985/140318703-a16e8961-3c86-4e63-96da-94047dd1d161.jpg)
![1 (4)](https://user-images.githubusercontent.com/58203985/140318707-a0ae163d-3a87-49ae-b924-af75d041b292.jpg)
![1 (5)](https://user-images.githubusercontent.com/58203985/140318711-9f1f0aa8-ab7e-4da0-8756-01e91ac3c9bc.jpg)
![2](https://user-images.githubusercontent.com/58203985/140319844-0455242d-36d8-4089-86dd-422562fc6595.jpg)
![1 (1)](https://user-images.githubusercontent.com/58203985/140318696-5a0ed499-a7de-47ba-9fec-d82736e51a68.jpg)
![1 (2)](https://user-images.githubusercontent.com/58203985/140318702-b6a5b817-1d00-457e-a361-808300f5f921.jpg)

**Device (please complete the following information):**
 - macOS Version: 11.6.1
 - EFI Version: 1.6.0
 - EFI type (regular or HeliPort): regular

**Additional context**
Thank you.

**Comment by BanannaFannaFoFax** [comment]
USB remap your ports.

**Comment by valnoxy** [comment]
Hey! 👋
It looks like you don't have a Intel WiFi card. Either you replace your wifi card, or you search for a suitable kext file, but I'm not sure if there any Realtek WiFi kexts exists.
