### ISSUE TITLE
What trackpad do you have installed ?

### ISSUE THREAD

**Issue by BanannaFannaFoFax** [valnoxy/t440p-oc#27]
Thanks for your hard work.
What trackpad do you have installed? I tried both the synaptic T450 and the regular one that the T440p comes with. They both don't allow me to scroll nor left click. Everything is Force Click and causes a preview to pop up.
Do you have the system settings trackpad preference panel working? Mine is blank.

**Comment by eob2000** [comment]
I had this exact same issue with mine (other than the fact that I *did* have the preference panel) all trackpad behaviour was the same. I am using the T450 synaptics trackpad (actually pulled from an L460 but afaik the trackpads are the same). What ended up fixing it for me was using https://github.com/VoodooSMBus/VoodooRMI in SMBus mode. If you have the synaptics trackpad I recommend giving that a go. It works great now, even gestures.

**Comment by Gopherslol** [comment]
Make sure you have disabled haptic feedback in trackpad settings. That breaks a lot of trackpad functionality

**Comment by valnoxy** [comment]
Hey 👋,
Thanks for your feedback! I've added VoodooRMI to this repo.
