### ISSUE TITLE
Multiple users support

### ISSUE THREAD

**Issue by dandycheung** [valnoxy/t440p-oc#28]
I installed Big Sur on my T440p with this EFI successfully. After that, I found one serious problem. I created two accounts, both admin. If I login one while another has logged in, I can not open any application, and the taskbar is invisible. I don not know if anybody else has encountered the same problem. Any suggestion?

**Comment by valnoxy** [comment]
Hey!
This error did not occur in my case. Could you try it with Version 1.7.0 again?

**Comment by dandycheung** [comment]
I'll try it when I'm not busy. Thank you.

**Comment by dandycheung** [comment]
Updated to v1.7.1 today, and that situation disappeared.
