### ISSUE TITLE
It is recommended to add IntelBluetoothFirmware to support Bluetooth and add Kext patch to support ultrabayhdd

### ISSUE THREAD

**Issue by yukigod17** [valnoxy/t440p-oc#3]
It is recommended to add IntelBluetoothFirmware to support Bluetooth and add Kext patch to support ultrabayhdd

IntelBluetoothFirmware[https://github.com/OpenIntelWireless/IntelBluetoothFirmware](url)

support ultrabayhdd
Kernel - Patch - Insert new row
![WX20210425-110726](https://user-images.githubusercontent.com/33057399/115979110-8772a300-a5b6-11eb-8307-0f2565b0cd75.png)

**Comment by valnoxy** [comment]
Thank you for your feedback! I have now added this in version 1.2.0.
