### ISSUE TITLE
Can i ask what every ssdt do

### ISSUE THREAD

**Issue by giovannidirenzo** [valnoxy/t440p-oc#30]
**Describe your question**
just asking out of curiosity, thanks in advance

**Comment by valnoxy** [comment]
Hey! 👋
I've added a short description about every SSDT in the readme. Here is a list:

- SSDT-ADPT ```(Power Resources for Wake)```
- SSDT-ALS0 ```(Fake ambient light sensor)```
- SSDT-BATX ```(Battery driver)```
- SSDT-DEHCI ```(Disable EHCI controller)```
- SSDT-ECRW ```(ACPI driver for OEM hardware (YogaSMC))```
- SSDT-HPET ```(IRQ Conflicts fix (Needs _CRS to XCRS Rename))```
- SSDT-KBD ```(Brightness patch)```
- SSDT-LED ```(LED and Power Button blink patch)```
- SSDT-MCHC ```(AppleSMBus fix)```
- SSDT-PLUG ```(Plugin type to 1 for CPU0/PR00)```
- SSDT-PNLF ```(PNLF device for WhateverGreen)```
- SSDT-PWRB ```(Power button)```
- SSDT-SMBUS ```(Injects missing DVL0 device)```
- SSDT-THINK ```(ThinkVPC (YogaSMC))```

The most of these SSDTs are needed for the kexts like YogaSMC and WhateverGreen.
