### ISSUE TITLE
there is not connected camera

### ISSUE THREAD

**Issue by azhhahahah** [valnoxy/t440p-oc#33]
it's been successful to install hackintosh on my laptop, but is the camera not connected. do you have a solution? my laptop is the same as yours
![Screen Shot 2021-12-15 at 21 39 17](https://user-images.githubusercontent.com/31090390/146206664-88a9a21c-f34a-444f-8b83-6a8bb7f3380b.png)

**Comment by valnoxy** [comment]
Hey,
could you try out Version 1.7.0? There was some issues with the USB mapping. Also make sure that you set your SMBIOS model to ```MacBookPro11,4``` while updating.
