### ISSUE TITLE
Language not changing

### ISSUE THREAD

**Issue by iknoors** [valnoxy/t440p-oc#35]
**Describe the bug**
When i change the language using proper tree, its still German

- macOS Version: 12 ( Monterey)

 - EFI type (regular or HeliPort): Monterey 

**Additional context**
No additional Context

**Comment by iknoors** [comment]
Here is my EFI Folder by the way

https://drive.google.com/file/d/1XhaOCQ-Mx534ZbiAfiDuP-_YUVJP5vqi/view?usp=sharing

**Comment by valnoxy** [comment]
Hey,
The layout must be separated with ```-``` rather than ```_```.
try replacing ```en_US:0``` with ```en-US:0```.

I will update the readme later.

**Comment by iknoors** [comment]
Nope. Its still not working

**Comment by valnoxy** [comment]
Hey, sorry for the late reply. 😅
You need to reset your NVRAM, but don't use the built-in reset function or your device will become soft-bricked.
I recommend updating the BIOS.
