### ISSUE TITLE
Bluetooth not switching on 

### ISSUE THREAD

**Issue by chiggo85** [valnoxy/t440p-oc#36]
**Note**: Please use the Discussions tab if you have any ideas or a question. 

**Describe the bug**
Bluetooth will not turn on - the toggle will not slide over. Found a crash report also. 

**Screenshots**
![image](https://user-images.githubusercontent.com/96927681/147848741-9cd9d4c1-d8ac-4494-98b5-cba160b609e0.png)
![image](https://user-images.githubusercontent.com/96927681/147848795-ab0ec466-8ffc-4a53-a070-91fedf37b9d5.png)

**Device (please complete the following information):**
![image](https://user-images.githubusercontent.com/96927681/147848751-4ebd6752-fa27-4762-8117-f0b09b924b0c.png)
￼
￼ - EFI type (regular or HeliPort): 
Regular
**Additional context**
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               bluetoothd [133]
Path:                  /usr/sbin/bluetoothd
Identifier:            bluetoothd
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               0

Date/Time:             2021-12-31 14:44:36.5002 +0000
OS Version:            macOS 12.1 (21C52)
Report Version:        12
Anonymous UUID:        ECD467BC-702E-1B33-8B27-388726A13B6F

Time Awake Since Boot: 70 seconds

System Integrity Protection: enabled

Crashed Thread:        4  Dispatch queue: com.apple.root.utility-qos

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff80a0a3aba mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7ff80a0a3e2b mach_msg + 59
2   CoreFoundation                	    0x7ff80a1a7af2 __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7ff80a1a61cb __CFRunLoopRun + 1325
4   CoreFoundation                	    0x7ff80a1a55dd CFRunLoopRunSpecific + 563
5   CoreFoundation                	    0x7ff80a22d62e CFRunLoopRun + 40
6   bluetoothd                    	       0x106934c86 0x10691c000 + 101510
7   dyld                          	       0x1083754fe start + 462

Thread 1::  Dispatch queue: com.apple.bluetooth.root
0   libsystem_kernel.dylib        	    0x7ff80a0a6506 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff80a0e0a69 _pthread_cond_wait + 1224
2   bluetoothd                    	       0x10698150b 0x10691c000 + 414987
3   bluetoothd                    	       0x1069c2d02 0x10691c000 + 683266
4   bluetoothd                    	       0x1069cf201 0x10691c000 + 733697
5   bluetoothd                    	       0x10697e731 0x10691c000 + 403249
6   bluetoothd                    	       0x106c5d09e 0x10691c000 + 3412126
7   bluetoothd                    	       0x106c5e235 0x10691c000 + 3416629
8   bluetoothd                    	       0x106c3d063 0x10691c000 + 3280995
9   libdispatch.dylib             	    0x7ff809f28ad8 _dispatch_call_block_and_release + 12
10  libdispatch.dylib             	    0x7ff809f29cc9 _dispatch_client_callout + 8
11  libdispatch.dylib             	    0x7ff809f2fcee _dispatch_lane_serial_drain + 696
12  libdispatch.dylib             	    0x7ff809f307fb _dispatch_lane_invoke + 417
13  libdispatch.dylib             	    0x7ff809f3a7e1 _dispatch_workloop_worker_thread + 758
14  libsystem_pthread.dylib       	    0x7ff80a0dd074 _pthread_wqthread + 326
15  libsystem_pthread.dylib       	    0x7ff80a0dbffb start_wqthread + 15

Thread 2:: StackLoop
0   libsystem_kernel.dylib        	    0x7ff80a0a5cf2 __psynch_mutexwait + 10
1   libsystem_pthread.dylib       	    0x7ff80a0dde8f _pthread_mutex_firstfit_lock_wait + 76
2   libsystem_pthread.dylib       	    0x7ff80a0dbd58 _pthread_mutex_firstfit_lock_slow + 204
3   bluetoothd                    	       0x10697e595 0x10691c000 + 402837
4   bluetoothd                    	       0x10697e9fd 0x10691c000 + 403965
5   libsystem_pthread.dylib       	    0x7ff80a0e04f4 _pthread_start + 125
6   libsystem_pthread.dylib       	    0x7ff80a0dc00f thread_start + 15

Thread 3:
0   libsystem_kernel.dylib        	    0x7ff80a0a6506 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff80a0e0a69 _pthread_cond_wait + 1224
2   bluetoothd                    	       0x106982fb6 0x10691c000 + 421814
3   libsystem_pthread.dylib       	    0x7ff80a0e04f4 _pthread_start + 125
4   libsystem_pthread.dylib       	    0x7ff80a0dc00f thread_start + 15

Thread 4 Crashed::  Dispatch queue: com.apple.root.utility-qos
0   libsystem_kernel.dylib        	    0x7ff80a0aa112 __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff80a0e0214 pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff80a02cd10 abort + 123
3   bluetoothd                    	       0x106e073a6 0x10691c000 + 5157798
4   bluetoothd                    	       0x10697ed92 0x10691c000 + 404882
5   libdispatch.dylib             	    0x7ff809f29cc9 _dispatch_client_callout + 8
6   libdispatch.dylib             	    0x7ff809f2c746 _dispatch_continuation_pop + 460
7   libdispatch.dylib             	    0x7ff809f3da5a _dispatch_source_invoke + 2150
8   libdispatch.dylib             	    0x7ff809f393ba _dispatch_root_queue_drain + 343
9   libdispatch.dylib             	    0x7ff809f39b5a _dispatch_worker_thread2 + 160
10  libsystem_pthread.dylib       	    0x7ff80a0dd02e _pthread_wqthread + 256
11  libsystem_pthread.dylib       	    0x7ff80a0dbffb start_wqthread + 15

Thread 5:
0   libsystem_pthread.dylib       	    0x7ff80a0dbfec start_wqthread + 0

Thread 4 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007000059a3000  rcx: 0x00007000059a2d48  rdx: 0x0000000000000000
  rdi: 0x0000000000002d0f  rsi: 0x0000000000000006  rbp: 0x00007000059a2d70  rsp: 0x00007000059a2d48
   r8: 0x0000000000000002   r9: 0x000000010717b000  r10: 0x0000000000000000  r11: 0x0000000000000246
  r12: 0x0000000000002d0f  r13: 0x0000000109004100  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007ff80a0aa112  rfl: 0x0000000000000246  cr2: 0x00007ff94d62bcc0
  
Logical CPU:     0
Error Code:      0x02000148 
Trap Number:     133

Binary Images:
    0x7ff80a0a3000 -     0x7ff80a0d9fff libsystem_kernel.dylib (*) <5aa1e5be-b5b8-3a02-9885-a8c99e0ca378> /usr/lib/system/libsystem_kernel.dylib
    0x7ff80a127000 -     0x7ff80a629fff com.apple.CoreFoundation (6.9) <eab0e216-2a9e-31ce-9164-fdf3ebcf7bd3> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x10691c000 -        0x106fcbfff bluetoothd (*) <5eea19ac-f95f-3684-acda-88b0c8194b3e> /usr/sbin/bluetoothd
       0x108370000 -        0x1083dbfff dyld (*) <cef5a27a-d50b-3020-af03-1734b19bc8c5> /usr/lib/dyld
    0x7ff80a0da000 -     0x7ff80a0e5fff libsystem_pthread.dylib (*) <6c7561b4-4b92-3f45-921e-abe669299844> /usr/lib/system/libsystem_pthread.dylib
    0x7ff809f27000 -     0x7ff809f6dfff libdispatch.dylib (*) <c8f7bfb6-4b1a-37cd-a32d-cd5069c916df> /usr/lib/system/libdispatch.dylib
    0x7ff809fab000 -     0x7ff80a033fff libsystem_c.dylib (*) <e58814cc-dcb7-35a5-badc-e367ed3ac207> /usr/lib/system/libsystem_c.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=916.7M resident=0K(0%) swapped_out_or_unallocated=916.7M(100%)
Writable regions: Total=155.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=155.5M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Dispatch continuations            64.0M        1 
Kernel Alloc Once                    8K        1 
MALLOC                            80.4M       29 
MALLOC guard page                   32K        8 
SQLite page cache                  128K        2 
STACK GUARD                       56.0M        6 
Stack                             10.5M        7 
VM_ALLOCATE                         36K        4 
__CTF                               759        1 
__DATA                            19.6M      383 
__DATA_CONST                      20.0M      245 
__DATA_DIRTY                      1181K      162 
__FONT_DATA                          4K        1 
__LINKEDIT                       641.8M        9 
__OBJC_RO                         81.8M        1 
__OBJC_RW                         3136K        2 
__TEXT                           274.9M      403 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
mapped file                       28.8M        7 
shared memory                      580K        6 
===========                     =======  ======= 
TOTAL                              1.3G     1281 

-----------
Full Report
-----------

{"app_name":"bluetoothd","timestamp":"2021-12-31 14:44:52.00 +0000","app_version":"","slice_uuid":"5eea19ac-f95f-3684-acda-88b0c8194b3e","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 12.1 (21C52)","incident_id":"61007248-04D0-40B6-94AA-CD16EF7E251E","name":"bluetoothd"}
{
  "uptime" : 70,
  "procLaunch" : "2021-12-31 14:43:31.4255 +0000",
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 0,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro11,4",
  "procStartAbsTime" : 3999066863,
  "coalitionID" : 121,
  "osVersion" : {
    "train" : "macOS 12.1",
    "build" : "21C52",
    "releaseType" : "User"
  },
  "captureTime" : "2021-12-31 14:44:36.5002 +0000",
  "incident" : "61007248-04D0-40B6-94AA-CD16EF7E251E",
  "bug_type" : "309",
  "pid" : 133,
  "procExitAbsTime" : 70886318994,
  "cpuType" : "X86-64",
  "procName" : "bluetoothd",
  "procPath" : "\/usr\/sbin\/bluetoothd",
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.apple.bluetoothd",
  "crashReporterKey" : "ECD467BC-702E-1B33-8B27-388726A13B6F",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 4,
  "threads" : [{"id":626,"queue":"com.apple.main-thread","frames":[{"imageOffset":2746,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":0},{"imageOffset":3627,"symbol":"mach_msg","symbolLocation":59,"imageIndex":0},{"imageOffset":527090,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":1},{"imageOffset":520651,"symbol":"__CFRunLoopRun","symbolLocation":1325,"imageIndex":1},{"imageOffset":517597,"symbol":"CFRunLoopRunSpecific","symbolLocation":563,"imageIndex":1},{"imageOffset":1074734,"symbol":"CFRunLoopRun","symbolLocation":40,"imageIndex":1},{"imageOffset":101510,"imageIndex":2},{"imageOffset":21758,"symbol":"start","symbolLocation":462,"imageIndex":3}]},{"id":1553,"queue":"com.apple.bluetooth.root","frames":[{"imageOffset":13574,"symbol":"__psynch_cvwait","symbolLocation":10,"imageIndex":0},{"imageOffset":27241,"symbol":"_pthread_cond_wait","symbolLocation":1224,"imageIndex":4},{"imageOffset":414987,"imageIndex":2},{"imageOffset":683266,"imageIndex":2},{"imageOffset":733697,"imageIndex":2},{"imageOffset":403249,"imageIndex":2},{"imageOffset":3412126,"imageIndex":2},{"imageOffset":3416629,"imageIndex":2},{"imageOffset":3280995,"imageIndex":2},{"imageOffset":6872,"symbol":"_dispatch_call_block_and_release","symbolLocation":12,"imageIndex":5},{"imageOffset":11465,"symbol":"_dispatch_client_callout","symbolLocation":8,"imageIndex":5},{"imageOffset":36078,"symbol":"_dispatch_lane_serial_drain","symbolLocation":696,"imageIndex":5},{"imageOffset":38907,"symbol":"_dispatch_lane_invoke","symbolLocation":417,"imageIndex":5},{"imageOffset":79841,"symbol":"_dispatch_workloop_worker_thread","symbolLocation":758,"imageIndex":5},{"imageOffset":12404,"symbol":"_pthread_wqthread","symbolLocation":326,"imageIndex":4},{"imageOffset":8187,"symbol":"start_wqthread","symbolLocation":15,"imageIndex":4}]},{"id":4086,"name":"StackLoop","frames":[{"imageOffset":11506,"symbol":"__psynch_mutexwait","symbolLocation":10,"imageIndex":0},{"imageOffset":16015,"symbol":"_pthread_mutex_firstfit_lock_wait","symbolLocation":76,"imageIndex":4},{"imageOffset":7512,"symbol":"_pthread_mutex_firstfit_lock_slow","symbolLocation":204,"imageIndex":4},{"imageOffset":402837,"imageIndex":2},{"imageOffset":403965,"imageIndex":2},{"imageOffset":25844,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":4},{"imageOffset":8207,"symbol":"thread_start","symbolLocation":15,"imageIndex":4}]},{"id":4088,"frames":[{"imageOffset":13574,"symbol":"__psynch_cvwait","symbolLocation":10,"imageIndex":0},{"imageOffset":27241,"symbol":"_pthread_cond_wait","symbolLocation":1224,"imageIndex":4},{"imageOffset":421814,"imageIndex":2},{"imageOffset":25844,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":4},{"imageOffset":8207,"symbol":"thread_start","symbolLocation":15,"imageIndex":4}]},{"triggered":true,"id":4658,"threadState":{"r13":{"value":4445978880},"rax":{"value":0},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":6},"rsi":{"value":6},"r8":{"value":2},"cr2":{"value":140708721900736},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":4413960192},"r15":{"value":22},"rbx":{"value":123145396301824},"trap":{"value":133},"err":{"value":33554760},"r11":{"value":582},"rip":{"value":140703297085714,"matchesCrashFrame":1},"rbp":{"value":123145396301168},"rsp":{"value":123145396301128},"r12":{"value":11535},"rcx":{"value":123145396301128},"flavor":"x86_THREAD_STATE","rdi":{"value":11535}},"queue":"com.apple.root.utility-qos","frames":[{"imageOffset":28946,"symbol":"__pthread_kill","symbolLocation":10,"imageIndex":0},{"imageOffset":25108,"symbol":"pthread_kill","symbolLocation":263,"imageIndex":4},{"imageOffset":531728,"symbol":"abort","symbolLocation":123,"imageIndex":6},{"imageOffset":5157798,"imageIndex":2},{"imageOffset":404882,"imageIndex":2},{"imageOffset":11465,"symbol":"_dispatch_client_callout","symbolLocation":8,"imageIndex":5},{"imageOffset":22342,"symbol":"_dispatch_continuation_pop","symbolLocation":460,"imageIndex":5},{"imageOffset":92762,"symbol":"_dispatch_source_invoke","symbolLocation":2150,"imageIndex":5},{"imageOffset":74682,"symbol":"_dispatch_root_queue_drain","symbolLocation":343,"imageIndex":5},{"imageOffset":76634,"symbol":"_dispatch_worker_thread2","symbolLocation":160,"imageIndex":5},{"imageOffset":12334,"symbol":"_pthread_wqthread","symbolLocation":256,"imageIndex":4},{"imageOffset":8187,"symbol":"start_wqthread","symbolLocation":15,"imageIndex":4}]},{"id":4910,"frames":[{"imageOffset":8172,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703297056768,
    "size" : 225280,
    "uuid" : "5aa1e5be-b5b8-3a02-9885-a8c99e0ca378",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703297597440,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5255168,
    "uuid" : "eab0e216-2a9e-31ce-9164-fdf3ebcf7bd3",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1856.105"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4405182464,
    "size" : 7012352,
    "uuid" : "5eea19ac-f95f-3684-acda-88b0c8194b3e",
    "path" : "\/usr\/sbin\/bluetoothd",
    "name" : "bluetoothd"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4432789504,
    "size" : 442368,
    "uuid" : "cef5a27a-d50b-3020-af03-1734b19bc8c5",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703297282048,
    "size" : 49152,
    "uuid" : "6c7561b4-4b92-3f45-921e-abe669299844",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703295500288,
    "size" : 290816,
    "uuid" : "c8f7bfb6-4b1a-37cd-a32d-cd5069c916df",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703296040960,
    "size" : 561152,
    "uuid" : "e58814cc-dcb7-35a5-badc-e367ed3ac207",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  }
],
  "sharedCache" : {
  "base" : 140703294054400,
  "size" : 15216738304,
  "uuid" : "40432a03-88d3-305f-9c0c-e7549e71d927"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=916.7M resident=0K(0%) swapped_out_or_unallocated=916.7M(100%)\nWritable regions: Total=155.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=155.5M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nDispatch continuations            64.0M        1 \nKernel Alloc Once                    8K        1 \nMALLOC                            80.4M       29 \nMALLOC guard page                   32K        8 \nSQLite page cache                  128K        2 \nSTACK GUARD                       56.0M        6 \nStack                             10.5M        7 \nVM_ALLOCATE                         36K        4 \n__CTF                               759        1 \n__DATA                            19.6M      383 \n__DATA_CONST                      20.0M      245 \n__DATA_DIRTY                      1181K      162 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       641.8M        9 \n__OBJC_RO                         81.8M        1 \n__OBJC_RW                         3136K        2 \n__TEXT                           274.9M      403 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nmapped file                       28.8M        7 \nshared memory                      580K        6 \n===========                     =======  ======= \nTOTAL                              1.3G     1281 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.root.utility-qos"
  }
},
  "trialInfo" : {
  "rollouts" : null,
  "experiments" : null
}
}

**Comment by VinylNerd** [comment]
which bluetooth card are you using?

**Comment by bi0shacker001** [comment]
I can second this, with some additional information.
The bluetooth card is sometimes off after boot, sometimes on. I cannot switch the power state regardless of where it's currently at, but it generally stays in that state through sleep (it'll, rarely, not turn on after sleep).
Willing to provide more information if necessary, but don't know what to provide.

**Comment by adithv08** [comment]
I am using a Wireless-AC 7260, and bluetooth just randomly freezes after sleep.
I can fix it by restarting the _bluetoothd_ process but this seems annoying as I use a Designer bluetooth mouse

**Comment by Baylandiego** [comment]
try to 

Intel WiFi/Bluetooth
OpenCore 0.7.8
Thinkpad T440p
The fix was:
UEFI -> ProtocolOverrides -> HashServices -> true
https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore/issues/150#issuecomment-1328252628
no issues after going sleep
