### ISSUE TITLE
Docking Station

### ISSUE THREAD

**Issue by Xeceryn** [valnoxy/t440p-oc#37]
**Describe the bug**
Bug was appear when Reboot or Sleep when plug in on Docking Station

**Device (please complete the following information):**
 - macOS Version: 11.6

**Comment by VinylNerd** [comment]
only happens when using display connected to docking station, this has been a longstanding issue with T440P Docking and Hackintosh

**Comment by Xeceryn** [comment]
> only happens when using display connected to docking station, this has been a longstanding issue with T440P Docking and Hackintosh

Thank you very much boss
