### ISSUE TITLE
bootable key does not start

### ISSUE THREAD

**Issue by iz7rjt** [valnoxy/t440p-oc#40]
I followed the guide perfectly but unfortunately when i insert the bootable key in my t440p it doesn't recognize opencore. I have set up my bios like guide and my bios is updated to the latest version of lenovo. Where am I wrong?

![977da97b-eba5-409c-acf4-aada1371c567](https://user-images.githubusercontent.com/76867226/149274270-f9105564-9db4-47f1-ace4-269be52c95f4.jpg)

**Comment by Zuchter** [comment]
Same issue here.

**Comment by valnoxy** [comment]
Hey, sorry for the late reply. 😅
You need to press SPACE to see the installer / tools.
I will update the README asap.
