### ISSUE TITLE
Unable to change language in config.plist

### ISSUE THREAD

**Issue by coolmanbat2** [valnoxy/t440p-oc#48]
Hi everyone, 

I changed my language on the config.plist "prev-kbd"; However, when I try to boot from the USB into the recovery partition. 

The language is still German, I'm not sure of the steps I need to take to fix this problem. Any insight is greatly appreciated.

Thank you.

**Comment by valnoxy** [comment]
Hey, you need to reset your NVRAM, but Thinkpad laptops are known to be semi-bricked after an NVRAM reset in OpenCore.
I recommend resetting NVRAM by updating the BIOS.

If this still doesn't work, try to set the following property:
NVRAM -> Delete -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> Item 0: Type ```String``` and Value ```prev-lang:kbd```
![OpenCore-Install-Guide](https://dortania.github.io/OpenCore-Install-Guide/assets/img/lang.cb258f4f.png)
