### ISSUE TITLE
Headphones buzzing noise

### ISSUE THREAD

**Issue by zJairO** [valnoxy/t440p-oc#5]
Hello, first of all, thank you for making this guide and repo.

Everything is working fine, I just found a buzzing noise when using headphones through auxiliar cable.

Tried to see if was a sound config, but no.

Also thank you for fixing the audio, now everything is working fine, only this thing.

Regards.

**Comment by tomassasovsky** [comment]
I have the same problem! It is a very loud buzzing sound.

**Comment by widiu7omo** [comment]
Try this https://github.com/Sniki/ALCPlugFix

or manually with 

./hda-verb 0x1a SET_PIN_WIDGET_CONTROL 0x24

**Comment by zJairO** [comment]
> Try this https://github.com/Sniki/ALCPlugFix
> 
> or manually with
> 
> ./hda-verb 0x1a SET_PIN_WIDGET_CONTROL 0x24

Hello, thanks for replying.

I already tried but I get this error:

zjairo@MacBook-Pro-de-zJairO ALCPlugFix-master % ./hda-verb 0x1a SET_PIN_WIDGET_CONTROL 0x24
nid = 0x1a, verb = 0x707, param = 0x24
Could not locate CodecCommander kext, ensure it is loaded.
command 0x01a70724 --> result = 0xffffffff

You know what is this about ? I have to install CodecCommander ?

**Comment by zJairO** [comment]
> Try this https://github.com/Sniki/ALCPlugFix
> 
> or manually with
> 
> ./hda-verb 0x1a SET_PIN_WIDGET_CONTROL 0x24

**Fixed!**

Had to install CodecCommander kext, then 

sudo spctl --master-disable
sudo mkdir /usr/local/bin/
cd desktop/ALCPlugFix
./install.sh

after that, your command.

hda-verb 0x1a SET_PIN_WIDGET_CONTROL 0x24

thank you man, now I have 100% functional hackintosh!

**Comment by tomassasovsky** [comment]
Can you please share the CodecCommander Kext link?
Thanks!

**Comment by zJairO** [comment]
https://mega.nz/folder/jlx0kIqC#oFg2Aso93iUThSHx-_DN0A

> Can you please share the CodecCommander Kext link?
> Thanks!

https://github.com/zJairO/t440p-oc/tree/main/EFI/OC/Kexts

On my fork.
Manually add the kext to config.plist

**Comment by tomassasovsky** [comment]
Will you do a Pull Request for this change?

**Comment by zJairO** [comment]
> Will you do a Pull Request for this change?

I can't do a push request to this repo, idk why

**Comment by valnoxy** [comment]
Thanks for your feedback! I include CodecCommander and ALCPlugFix in version 1.2.1.

**Comment by tomassasovsky** [comment]
CodecCommander.kext makes my macOS not boot, i can't get past the Apple logo screen. I'm using macOS Big Sur

**Comment by VinylNerd** [comment]
Last login: Tue Nov 30 13:00:04 on ttys000
Connor@Connors-MBP-2 ~ % sudo spctl --master-disable
Password:
Connor@Connors-MBP-2 ~ % sudo mkdir /usr/local/bin/ 
mkdir: /usr/local/bin/: File exists
Connor@Connors-MBP-2 ~ % cd Desktop/ALCPlugFix      
Connor@Connors-MBP-2 ALCPlugFix % ./install.sh               
Installing ALCPlugFix v1.7
Stopping existing ALCPlugFix daemon.
Done!
Connor@Connors-MBP-2 ALCPlugFix % hda-verb 0x1a SET_PIN_WIDGET_CONTROL 0x24
nid = 0x1a, verb = 0x707, param = 0x24
Could not locate CodecCommander kext, ensure it is loaded.
command 0x01a70724 --> result = 0xffffffff
Connor@Connors-MBP-2 ALCPlugFix %

i have codec commander installed but still not working on 11.6.1
