### ISSUE TITLE
Can I upgrade to Monterey?

### ISSUE THREAD

**Issue by iknoors** [valnoxy/t440p-oc#53]
I want to upgrade to the latest and the greatest, but how? I suppose putting the Monterey EFI folder when Software Update downloads mac os. Then I can continue.

**Comment by valnoxy** [comment]
Hey 👋,

You can change the EFI after upgrading to Monterey. Just follow the instruction "Installation -> ♻️ Upgrade macOS / Switch EFI" on the repo:

1. Start ProperTree and load the Config.plist on your EFI partition. (File -> Open)
>Note: You can mount your EFI partition by pressing ALT + SPACE, typing Terminal and enter the following command: sudo diskutil mountDisk disk0s1.

2. Now also load the new configuration file from the repo for the desired macOS installation (or HeliPort config).

3. You should now have 2 ProperTree-windows open on your screen.

4. Go in both windows to ```Root -> PlatformInfo -> Generic```. Transfer MLB, ROM, SystemProductName, SystemSerialNumber and SystemUUID to the new config.

5. Save the new config (File -> Save) and close both windows.

6. Now delete your existing EFI folder from the EFI partition and copy the new one to it. (Make sure that the directories ```Boot``` and ```OC``` are in EFI).
