### ISSUE TITLE
Iservice issue

### ISSUE THREAD

**Issue by SolomonPeggs** [valnoxy/t440p-oc#6]
Hey, my iMessage and facetime aren't working. It keeps signing me out right after I sign in. I already reissued my MLB, SPN, SSN, and UUID, but that didn't work. Is there any fix? (I'm on Big Sur)

**Comment by yukigod17** [comment]
See this page, solve your problem
https://github.com/valnoxy/t440p-oc#gensmbios

**Comment by valnoxy** [comment]
Hey! 👋
Try to follow this guide: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html

**Comment by Zuchter** [comment]
I have the same issue as the other person
