### ISSUE TITLE
Bluetooth not working

### ISSUE THREAD

**Issue by ryadhiprasetya** [valnoxy/t440p-oc#7]
![Screen Shot 2021-06-20 at 11 23 39](https://user-images.githubusercontent.com/47018482/122662026-0d2b5d00-d1ba-11eb-9624-e7390fce70b4.png)

I'm not edit anything on config.plist, except gmbios

**Comment by valnoxy** [comment]
Which macOS Version do you use?

**Comment by ryadhiprasetya** [comment]
right now i use version 11.4
i was solve this issue. remove airportitlwm and add itlwm.kext & heliport.
i update intelbluetooth too.
