### ISSUE TITLE
WWAN Sierra Wireless EM7345

### ISSUE THREAD

**Issue by drizzo0** [valnoxy/t440p-oc#73]
The WWAN Module Sierra Wireless EM7345 is showing as ethernet and not working
I'm using Monterey.
I'll attempt to fix the kext responsible and I'll keep this issue updated with my progress

**Comment by asahiba** [comment]
i need this

**Comment by drizzo0** [comment]
Unfortunately, after too many tries, sadly I have to come to the conclusion that the EM7345 is not supported..
So the only way to go could be modding the bios and using another card but at the moment I don't have time, hardware and resources to do it.
