### ISSUE TITLE
Built-in Camera doesn't work

### ISSUE THREAD

**Issue by EdsonLuiz** [valnoxy/t440p-oc#9]
- MacOS: 11.4
- EFI Folders tested:
  - EFI - Big Sur
  - EFI - HeliPort
- bios settings are ok
  
I have no technical knowledge to find the cause of this problem.

![Screen Shot 2021-07-01 at 23 04 54](https://user-images.githubusercontent.com/5461553/124281665-510a5480-db20-11eb-8351-ecbfec4d4922.png)

**Comment by valnoxy** [comment]
Thank you for your feedback! I fixed the bug with Version 1.5.0!
